### PR TITLE
Massive cleanup

### PR DESCRIPTION
**Pull request by malte-v**
Things done:

- By @purefn: Added support for plain authentication
- Updated some code to work with recent versions of the networking package
- Moved everything from Web.Postie to Network.Mail.Postie (email doesn't have much to do with the web ;))
- Cleaned up remaining compiler and HLint warnings
- Formatted everything
- Added Nix support (now compiles with nixpkgs-unstable)

The new networking code seems to be working fine. I'm able to have an SMTP session with the server via telnet on both IPv4 and IPv6.

A major release on Hackage after this gets merged would be much appreciated!

### CODE REVIEW

**Comment by alexbiehl** [comment]
Awesome! Great work. Do you think we should remove the stupid session uuid thing as well? I always found it to be strange. Wonder how we would organize it differently but maybe you have an idea.

**Review by alexbiehl — APPROVED** [review]
Fire away!

**Comment by malte-v** [comment]
> Do you think we should remove the stupid session uuid thing as well?

Not sure... What was the rationale for introducing it? I honestly don't know much about SMTP at all, I just want to receive some email so I'm probably not the best person to ask.

**Comment by malte-v** [comment]
Oh sure, it's for keeping the clients apart. I think we do need some sort of session identifier for that, so I would just leave it as is.

**Comment by malte-v** [comment]
So can you merge and release this now? :3

**Comment by alexbiehl** [comment]
What's your hackage handle?

**Comment by malte-v** [comment]
It's `malvo`. I don't have upload permissions yet though because the Hackage mailserver doesn't accept my email :/

**Comment by alexbiehl** [comment]
You are now a maintainer for postie on hackage. I won't be around a computer for the next two weeks.

**Comment by malte-v** [comment]
Great, thanks!

**Pull request merged**
